spring:
  r2dbc:
    url: r2dbc:postgresql://wallet:wallet@db:5432/wallet
    username: wallet
    password: wallet
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      default-schemas: wallet_schema

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml